#!/usr/bin/env python

import montemodes.functions.reading as io_monte
import montemodes.functions.montecarlo as monte
import montemodes.functions.methods as method
import  montemodes.classes.results as res
import montemodes.functions.symop as symop
import montemodes.functions.shape as shape

#Define energy calculation methodology
gaussian_calc = method.gaussian(methodology='pm6',
                               internal=False)

#Define MC simulation conditions
conditions = res.Conditions(temperature=500,
                            number_of_cycles=5,
                            initial_expansion_factor=0.05,
                            acceptation_regulator=0.1,
                            number_of_values_for_average=5,
                            energy_method=gaussian_calc)

#Read initial structure from xyz file
molecule = io_monte.reading_from_xyz_file('../Example/test.xyz')

#Add additional information to molecule
molecule.charge = 0
molecule.multiplicity = 1

#Create MD simulation object from molecule
simulation = res.MonteCarlo(molecule)

#Run Monte Carlo simulation with cartesian algorithm using simulation object & conditions
result = monte.calculate_MonteCarlo(simulation, conditions,
                                    show_text=True,
                                    alteration_type='cartesian')

#Save results to data files
io_monte.write_result_to_file(result, 'test.out')
io_monte.write_result_trajectory(result.trajectory, 'trajectory.xyz')


#Shape analysis
shape_m1 = shape.Shape(code=1,
                       custom_atom_list=[4, 5, 6, 7],
                       central_atom=0)

shape_m2 = shape.Shape(code=2,
                       custom_atom_list=[4, 5, 6, 7],
                       central_atom=0)


shape_list_m1 = shape.get_shape_trajectory(result.trajectory, shape_m1)
shape_list_m2 = shape.get_shape_trajectory(result.trajectory, shape_m2)

io_monte.write_list_to_file(zip(shape_list_m1,shape_list_m2), 'shape.txt')




#Symmetry analysis
symop_c3 = symop.Symop(symmetry='c 3',
                       label=False,
                       connect=False,
                       central_atom=0)

symmetry_list = symop.get_symmetry_trajectory(result.trajectory, symop_c3)
io_monte.write_list_to_file(symmetry_list, 'symmetry.txt')


#Save full simulation to file (contains all data) [Can be used to restart the simulation]
io_monte.save_to_dump(conditions, result, filename='full.obj')

io_monte.load_from_dump(filename='full.obj')