#!/usr/bin/env python

import montemodes.functions.reading as io_monte
import montemodes.functions.montecarlo as monte
import montemodes.functions.methods as method

#Define energy calculation methodology
import  montemodes.classes.results  as res

gaussian_pm6 = method.gaussian(methodology='pm6',
                               internal=False)
#Define MC simulation conditions
conditions = res.Conditions(temperature=500,
                            number_of_cycles=50,
                            initial_expansion_factor=0.05,
                            acceptation_regulator=0.1,
                            number_of_values_for_average=50,
                            energy_method=gaussian_pm6)

#Read initial structure from xyz file
molecule = io_monte.reading_from_xyz_file('test.xyz')

#Add additional information to molecule
molecule.charge = 0
molecule.multiplicity = 1

#Create MD simulation object from molecule
simulation = res.MonteCarlo(molecule)

#Run Monte Carlo simulation with cartesian algorithm using simulation object & conditions
result = monte.calculate_MonteCarlo(simulation, conditions)


#Save results to data files
io_monte.write_result_to_file(result, 'test.out')
io_monte.write_result_trajectory(result.trajectory, 'trajectory.xyz')

#Save full simulation to file (contains all data) [Can be used to restart the simulation]
io_monte.save_to_dump(conditions, result, filename='full.obj')

